### PR TITLE
bump kotlin

### PR DESCRIPTION
**Pull request by meoyawn**

### CODE REVIEW

**Comment by hastebrot** [comment]
This PR bumps to Kotlin 1.0.1-2. In the meantime Kotlin 1.0.2 was released.

**Comment by meoyawn** [comment]
@hastebrot yeah, sigh... :)

**Comment by winterbe** [comment]
Thanks. I'm going to deploy a new version to Maven Central probably this weekend.

**Comment by meoyawn** [comment]
woo-hoo!

**Comment by hastebrot** [comment]
```
<kotlin.version>1.0.2</kotlin.version>
<dokka.version>0.9.7</dokka.version>
```

Hmm, Kotlin 1.0.2 also needs the new Dokka version 0.9.8.

> Together with Kotlin 1.0.2, we’re releasing a new version of Dokka, the Kotlin documentation generation tool. If you’re using Dokka in your project, you need to upgrade Dokka together with Kotlin, because older Dokka versions are incompatible with Kotlin 1.0.2.

via: https://blog.jetbrains.com/kotlin/2016/05/kotlin-1-0-2-is-here/

**Comment by meoyawn** [comment]
whoops, we should probably add dokka generation to travis checks

**Comment by winterbe** [comment]
Yep you right. Whole API doc is still a work in progress. We should bump the dokka version and publish the docs somewhere when it's in a solid state.

Unfortunately I had not much time for Kotlin dev lately but hopefully this will change soon. However I happily accept pull requests. 👯

**Comment by winterbe** [comment]
New version 0.4.0 is available in Maven Central. I've also updated the Dokka version.

**Pull request merged**
